### ISSUE TITLE
KDE - Dolphin Manager not showing correctly

### ISSUE THREAD

**Issue by KubiGR** [Mrcuve0/Aritim-Dark#10]
I have downloaded and installed Aritim dark for KDE. When I apply the desktop theme, the dolphin manager (the one on the taskbar but plus all the other ones as well) are opening and they throw an "unknown application folder". Also when I hover the dolphin manager icon, the title is a very long string.

**Comment by Mrcuve0** [comment]
Thank you for pointing that issue out.
As for now, you may want to re-adjust manually the overall panel as you prefer.

The buggy plasmoid is called "Icons-only task manager": you can remove manually every icon/application pinned in it and finally pin your applications you may want to access quickly later. As for now this is the only way, sadly. To do that right-click on the faulty icon and click on "Unpin from task manager". Once you removed all the broken icons/applications, you can pin yours as you open the corresponding application (again, right click on the icon + pin on the task manager) or by left-clicking on the KDE "Start" button, right-clicking on an application name and select "+ Add to panel (Widget)".

I think I'll remove this plasmoid in the next release since it causes general confusion and let the user decide for the applications he/she may want to pin.

Hope this helps! :D

PS: If you have an account, you may want to leave a rating on my theme at the following page, it means a lot to me, thanks! --> https://www.pling.com/p/1281836/

**Comment by KubiGR** [comment]
Yeah that worked. I though it was the actual manager because the icon theme was also missing (now installed papirus and the recent folders are showing up fine). I will go and leave a rating because this is very good user experience.

**Comment by Mrcuve0** [comment]
Glad everything worked and thank you very much! I'll close this issue later so I'll remember to remove the task manager from the theme in the next days :)

**Comment by Mrcuve0** [comment]
Icons removed
