### ISSUE TITLE
White texts are hard to read when the windown behind is white

### ISSUE THREAD

**Issue by messiaslimarethink** [Mrcuve0/Aritim-Dark#12]
**Is your feature request related to a problem? Please describe.**
In low-quality screens (like mine), is hard to read the white text on widgets above white screens

**Describe the solution you'd like**
Make the widget's background darker as the konsole theme, would be awesome for us.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/61054749/79731846-c35f9200-82ea-11ea-8bf3-8642a0aaa15b.gif)

**Comment by Mrcuve0** [comment]
Thank you for making the GIF, I totally got your point.

This is what I see from my system, and it seems it is way more readable than your version
![Screenshot_20200420_111137](https://user-images.githubusercontent.com/36898760/79734881-b8f7c500-82f7-11ea-9650-a9a73d3c2a62.png)

This screenshot however is a new version I completed a week ago and I have not uploaded it yet on the KDE Store.
It is called `Aritim-Dark-Flat-Blur`. Since the name has changed you may have to download it from scratch and remove the old version you actually have. 
I'm uploading it right now, check it and see if the problem is solved also on your side.

Let me know! And thank you for your feedback!

**Comment by Mrcuve0** [comment]
Ok here it is: 

> https://www.pling.com/p/1309107

I checked and you can now download it from `System Settings` --> `Plasma Style` --> `Get new plasma style`.

![Screenshot_20200420_114757](https://user-images.githubusercontent.com/36898760/79738240-ca8f9b80-82fc-11ea-9e46-c2a7cc433e28.png)

**Comment by messiaslimarethink** [comment]
It is now perfect! Thank you so much! You are the best
