### ISSUE TITLE
Strange visuals in Aritim-Dark-Flat-Blur Style

### ISSUE THREAD

**Issue by Sebastriani** [Mrcuve0/Aritim-Dark#18]
**Describe the bug**
I'm not sure whether this is a bug or an expected modification that I just probably got in an update.
The Plasma Style "Aritim-Dark-Flat-Blur" suddenly changed visuals.

**To Reproduce**
- Start with other Global Theme than Aritim-Dark
- Go to "System Settings" -> "Appearance"
- If you don't have Aritim-Dark installed, install it.
- Apply the theme
- Go to the "Plasma Style" menu and apply "Aritim-Dark-Flat-Blur"

**Expected behavior**
The expected behaviour is to have the same visuals as "Aritim-Dark-Flat-Solid" but with a slightly trasparent kick-off

**Screenshots**

Expected Style (mouse selection highlight, opened applications in taskbar)
![Screenshot_20210605_181728](https://user-images.githubusercontent.com/28619741/120905722-6a57d800-c62a-11eb-9f08-3caa5553794b.png)

Actual Style
![Screenshot_20210605_181516](https://user-images.githubusercontent.com/28619741/120905670-164cf380-c62a-11eb-8443-fa82771d6286.png)

**Desktop (additional informations):**
 - OS: KDE Neon 5.21

(if you are using KDE)
 - KDE Plasma Version: 5.21.5
 - KDE Frameworks Version: 5.82.0

**Additional context**
Another weird thing, previously, Firefox didn't got applied the "Aritim-Dark" Windows Decorations in the Titlebar Buttons, now it does:

![Screenshot_20210605_182527](https://user-images.githubusercontent.com/28619741/120905864-6d9f9380-c62b-11eb-8b8d-9da31404d45d.png)

EDIT1: I don't have "Aritim Light" installed, I never had and I just read the instructions there are here in the repo.
It was very nice anyway without "Aritim Light"

EDIT2: Sorry I just realize it's actually "Lightly" and not "Aritim-Light" what's pointed in the instructions, anyway I won't install that one, I liked just as I had it, simply installing Aritim-Dark.

**Comment by Sebastriani** [comment]
Mmm I think I'm starting to get it.

Is it possible that for some reason "Aritim-Dark-Flat-Blur" got the "real" decorations and previously it was taking some from Breeze-Dark? And that "Aritim-Dark-Flat-Solid" is still borrowing some styles from "Breeze-Dark"?

**Comment by Mrcuve0** [comment]
Yep I updated it today, everything (well, mostly haha) is intentional (https://twitter.com/mrcuve0/status/1401138881957928964?s=20).

Basically I tried to modernize the look adding rounded corners and improve a little bit the readability. Sadly I just noticed the bottom oval in the task bar, that is not supposed to happen and it's something I forgot to test (I use the icon only task manager, the one with just the icons).

Now, did you prefer the old look or its the oval that bothers you? In the first case I can create another plasma theme that reflects the "old" look so that you (and others) can install that (that's probably what I'll do in the next days, so to give the user as much choice as possible)

**Comment by Mrcuve0** [comment]
Lightly is just an optional component (window decorations) that the user can decide to install or not, so if you don't like it don't worry, you can keep the previous look. It's just suggested in the readme in the case the user may want to match exactly the screenshots I made, maybe I should specify in a clearer way?

---

For what regards Firefox I tend to believe that's due to the latest 89 update, the one that made various graphical changes *tabs menus etc). Sadly for now I can't confirm this theory by myself as Opensuse still has not pushed the update.

**Comment by Mrcuve0** [comment]
Aritim-Dark-Flat-Solid is still at the previous version, yes. I still have to update it as I need to further check KDE documentation.

So yeah, in summary, nearly everything was planned ahah. Let me know if you think I should fork the new version from the old one, so you can still have the old one available.
I could probably manage them like this:

* Aritim-Dark-Flat-Blur --> revert back the old version
* Aritim-Dark-Flat-Solid --> rever back the old version
* Aritim-Dark-Rounded-Blur --> new version (to be forked)
* Aritim-Dark-Rounded-Solid --> new version (to be forked)

(sorry for all these notifications)

**Comment by Sebastriani** [comment]
@Mrcuve0 I really appreciate your work, I still have to find a better Dark Theme than Aritim, I haven't changed it since I started using KDE 10 months ago. In the screenshots you can see that I've tried Gently and KDE Story (other's as well) but nop... I kept Aritim.

It would be really nice if you could keep the old version as you say, kind of a different style.
One thing I think I forgot to comment is that the current version of "Aritim-Dark-Flat-Blur" has also lost the transparent kick-off.

It took me a while to notice the differences, I just perceived something was wrong, now I can tell you exactly that what I miss from the old Style is that to me, it was perfect to first apply Breeze Dark and then Aritim-Dark with Aritim-Dark-Flat-Blur on top of it.

So, it would actually be the same as right now applying "Aritim-Dark-Flat-Solid" with the difference that I miss the Kick-off transparency that Aritim-Dark-Flat-Blur had.

![Screenshot_20210605_235935](https://user-images.githubusercontent.com/28619741/120911050-65ab1800-c65a-11eb-87fd-d74c6fd6a1e1.png)

![Screenshot_20210606_000057](https://user-images.githubusercontent.com/28619741/120911055-72c80700-c65a-11eb-9644-6572c921ab9c.png)

What I'm miss I think is actually part of Breeze-Dark which it seems now you are overwriting it when previously you did not.

**Comment by Mrcuve0** [comment]
> It would be really nice if you could keep the old version as you say, kind of a different style.

Yep the best thing to do is keep the "old" version in parallel with the new one, you are definitely not the only one that may prefer the old look!
I'm working on it right now, I'll reply to this thread when ready!

> What I'm miss I think is actually part of Breeze-Dark which it seems now you are overwriting it when previously you did not.

Yeah the old version inherited most (if not all) the SVGs from Breeze and Breeze-Dark, only the colors change actually. It was a nice way to keep something as default as possible but also a little bit customized

**Comment by Mrcuve0** [comment]
Ok I made all the packages like mentioned above.
There's probably still some cache issue on the OpenDesktop side (it takes a while for the modifications to reflect on System Settings webpage). You can however download them directly from the site:

* [Aritim-Dark Rounded Solid](https://www.pling.com/p/1534821/)
* [Aritim-Dark Rounded Blur](https://www.pling.com/p/1534788/)
* [Aritim-Dark Flas Blur](https://www.pling.com/p/1309107/)
* [Aritim-Dark Flas Solid](https://www.pling.com/p/1312804/)

Let me know if everything is back to normal!

**Comment by Sebastriani** [comment]
@Mrcuve0 Thank you very much, I really appreciate it, now it's just as before.
The four styles are already available from the KDE settings "Plasma Style"

![Screenshot_20210606_233718](https://user-images.githubusercontent.com/28619741/120951969-702fe500-c720-11eb-9263-cbce76f8ab73.png)

One more comment, although I won't be using it, I've noticed that the new "Rounded-Blur" style, has a lighter Kick-off and Task Manager color than the "Flat-Blur" whereas the "Rounded-Solid" style maintains the darker color of the "Flat" styles, probably you meant it that way, but just in case I let you know.

Thank you!

**Comment by Mrcuve0** [comment]
> probably you meant it that way, but just in case I let you know.

Let's say it's intentional ahah. The fact is that Rounded-Blur has been created from scratch whereas Flat-Blur was simply modified from Breeze. Also, at that time, I was an Inkscape newbie and even now I can't actually understand what were the steps I did to obtain that exact appearance. The final result is ok but the SVGs are a little bit messy :D 

> Thank you!

No problem! Have a nice day!
